### ISSUE TITLE
Map AQL to Argument

### ISSUE THREAD

**Issue by jinxcifer** [OKNoah/final-orm#19]
Hi,

I am using the following function:

```
User.findOne({where: {email: email, username: username}})
```

With this query, I get the first user which has the specified email AND username (if there is one), right? Is it also possible to specify that I want to get the first user who has the specified email OR username? If it's possible, what do I have to pass as parameter?

Thanks in advance!

Best regards,
Jinxcifer

**Comment by jinxcifer** [comment]
@OKNoah Thanks for your fast answer!

The use case is quite simple: When a user registers at my web page, the user has to enter username, email and password. Before adding the user to the database, I want to check if either the username or the email already exist and prompt the user if there is a duplicate.

It is not urgent, but if there is no such feature in the next weeks/months, I might have to switch.

Best regards,
Jinxcifer

**Comment by OKNoah** [comment]
@jinxcifer Be glad you asked, there is a much better way! You can define your `username` and `email` fields as unique. So the database will automatically disallow documents where those fields are identical.

Check out this test: https://github.com/OKNoah/final-orm/blob/master/index.test.js#L17

```js
class User extends db.Model {
  static schema = {
    name: { $type: String, index: true, unique: true }, // <-- see the 'unique' key here. You may also need 'index', I forget :p
    profile: {
      vegan: { $type: Boolean, optional: true }
    }
  }
}
```

Then one way of using this is like

```js
try {
    await User.add({ name: username })
  } catch (error) {
    // arango will throw a message saying what info is duplicate
  }
```

Word of caution: if you _already have_ duplicate username and emails in your documents, Arango will not work well after making this change. If that is the case, you'll have to find them using an AQL query and delete or change duplicate documents. I've had to do this before, and it's not too hard to write such a query, depending on whether it's a live site with important data or not.

Let me know if this resolves your issue! :)

**Comment by OKNoah** [comment]
@jinxcifer My pleasure, enjoy :)

**Comment by OKNoah** [comment]
@jinxcifer Hey, would you mind giving a "star" to the project if you like it? Top right of the page. No big deal though if you only reserve your stars for the best. Take care.
